### ISSUE TITLE
Does this plugin still work in December 2020?

### ISSUE THREAD

**Issue by johnspurlock** [Automattic/pushpress#12]
I'm finding a few podcast feeds out there with pushpress hubs.  None of them seem to respond to proper subscribe calls.

e.g. `POST` to `http://f16cradio.wordpress.com/?pushpress=hub` with `Content-Type: application/x-www-form-urlencoded` and body `hub.mode=subscribe&hub.topic=http%3A%2F%2Ffeeds.feedburner.com%2FFunky16cornersRadioShow&hub.callback=https%3A%2F%2Felided&hub.verify=sync&hub.lease_seconds=3456000&hub.secret=elided`

yields a 400 response with body `hub.callback is empty`

Same thing for hub `http://cordkillersaudio.wordpress.com/?pushpress=hub` and topic `http://feeds.feedburner.com/Cordkillers`

Happy to provide a workaround in my client to get these to work if necessary, any ideas?

**Comment by dd32** [comment]
Hi @johnspurlock - Apologies for the delay in response.

I'm not sure if this is still an issue, but I can't reproduce it, with the above payload you should currently receive a response such as:
```
HTTP/1.1 400 Bad Request

hub_topic - http://feeds.feedburner.com/Funky16cornersRadioShow - is value is not allowed.  You may only subscribe to https://f16cradio.wordpress.com/feed/ or https://f16cradio.wordpress.com/feed/atom/
```

If you're seeing anything else, please contact WordPress.com support via https://wordpress.com/support/ with some details.
