### ISSUE TITLE
RSS feed is not rendered as a RSS feed

### ISSUE THREAD

**Issue by dd32** [Automattic/pushpress#13]
It appears that the RSS feed pushed to other sites, doesn't trigger `is_feed()` to be truthful:

https://meta.trac.wordpress.org/ticket/5533

The code in the plugin in question uses `is_feed()`:
https://plugins.trac.wordpress.org/browser/wporg-glossary/trunk/includes/class-glossary-handler.php?marks=72#L65

I think this can just be changed to `query_posts( "p={$post_id}&feed={$feed_type}" );` maybe?
https://github.com/Automattic/pushpress/blob/trunk/send-ping.php#L43

```
wp> query_posts( "p=12512" );
...
wp> $wp_query->is_feed();
bool(false)
wp> is_feed();
bool(false)

wp> query_posts( "p=12512&feed=rss2" );
...
wp> $wp_query->is_feed();
bool(true)
wp> is_feed()
bool(true)
```

I haven't tested this with the plugin yet, and I could update the `wporg-glossary` plugin to also prevent filtering during cron events, but regardless, ensuring `is_feed()` returns correctly seems like a worthy change.

_Just noting, I've pushed this change onto WordPress.org for testing._

**Comment by Krinkle** [comment]
I can confirm that the observed issue that has plagued make.wordpress.org feeds throughout the past year, has been resolved for me. (Details at https://github.com/FreshRSS/FreshRSS/issues/4302)

Thank you!
